Add functions for general multi-dimensonal processing.
nion-software/niondata pull request #42
Opened 2022-09-08 08:30 UTC by Brow71189

2022-09-08 22:03 UTC, cmeyer requested changes

2022-09-08 22:03 UTC, cmeyer commented on nion/data/MultiDimensionalProcessing.py
> +                                              bounds: typing.Optional[typing.Union[typing.Tuple[float, float], typing.Tuple[typing.Tuple[float, float], typing.Tuple[float, float]]]] = None,
Can you use `Core.NormRectangleType` and `Core.NormIntervalType` here?

2022-09-12 14:55 UTC, Brow71189 commented
All done.

2022-09-12 17:10 UTC, cmeyer commented
Merged 542fa59344b830e412a42f72d39e5ebec83d58c9
Minor edits (removed outdated Graphic typing comment, some minor formatting, CHANGES file, misspelling in commit message).

2022-09-12 17:10 UTC, closed without merging